import { Directions, Locations, Stage } from "../types";

export const stages: Stage[] = [
  {
    location: Locations.Argentina,
    direction: Directions.Forward,
    name: "Las Juntas",
    distance: "8.25",
    id: 0,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Forward,
    name: "Valle de los puentes",
    distance: "7.98",
    id: 1,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Forward,
    name: "Camino de acantilados y rocas",
    distance: "5.30",
    id: 2,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Forward,
    name: "San Isidro",
    distance: "4.48",
    id: 3,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Forward,
    name: "Miraflores",
    distance: "3.35",
    id: 4,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Forward,
    name: "El Rodeo",
    distance: "2.84",
    id: 5,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Reverse,
    name: "Camino a La Puerta",
    distance: "8.25",
    id: 6,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Reverse,
    name: "Valle de los puentes a la inversa",
    distance: "7.98",
    id: 7,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Reverse,
    name: "Camino de acantilados y rocas inverso",
    distance: "5.30",
    id: 8,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Reverse,
    name: "Camino a Coneta",
    distance: "4.48",
    id: 9,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Reverse,
    name: "Huillaprima",
    distance: "3.35",
    id: 10,
  },
  {
    location: Locations.Argentina,
    direction: Directions.Reverse,
    name: "La Merced",
    distance: "2.84",
    id: 11,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Mount Kaye Pass",
    distance: "12.50",
    id: 12,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Chandlers Creek",
    distance: "12.34",
    id: 13,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Bondi Forest",
    distance: "7.01",
    id: 14,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Rockton Plains",
    distance: "6.89",
    id: 15,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Yambulla Mountain Ascent",
    distance: "6.64",
    id: 16,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Noorinbee Ridge Ascent",
    distance: "5.28",
    id: 17,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Mount Kaye Pass Reverse",
    distance: "12.50",
    id: 18,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Chandlers Creek Reverse",
    distance: "12.34",
    id: 19,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Taylor Farm Sprint",
    distance: "7.01",
    id: 20,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Rockton Plains Reverse",
    distance: "6.89",
    id: 21,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Yambulla Mountain Descent",
    distance: "6.64",
    id: 22,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Noorinbee Ridge Descent",
    distance: "5.28",
    id: 23,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Forward,
    name: "Waimarama Point Forward",
    distance: "16.06",
    id: 24,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Forward,
    name: "Te Awanga Forward",
    distance: "11.48",
    id: 25,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Forward,
    name: "Waimarama Sprint Forward",
    distance: "8.81",
    id: 26,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Forward,
    name: "Elsthorpe Sprint Forward",
    distance: "7.32",
    id: 27,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Forward,
    name: "Ocean Beach Sprint Forward",
    distance: "6.61",
    id: 28,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Forward,
    name: "Te Awanga Sprint Forward",
    distance: "4.79",
    id: 29,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Reverse,
    name: "Waimarama Point Reverse",
    distance: "16.06",
    id: 30,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Reverse,
    name: "Ocean Beach",
    distance: "11.48",
    id: 31,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Reverse,
    name: "Waimarama Sprint Reverse",
    distance: "8.81",
    id: 32,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Reverse,
    name: "Elsthorpe Sprint Reverse",
    distance: "7.32",
    id: 33,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Reverse,
    name: "Ocean Beach Sprint Reverse",
    distance: "6.61",
    id: 34,
  },
  {
    location: Locations.NewZealand,
    direction: Directions.Reverse,
    name: "Te Awanga Sprint Reverse",
    distance: "4.79",
    id: 35,
  },
  {
    location: Locations.Spain,
    direction: Directions.Forward,
    name: "Comienzo De Bellriu",
    distance: "14.34",
    id: 36,
  },
  {
    location: Locations.Spain,
    direction: Directions.Forward,
    name: "Centenera",
    distance: "10.57",
    id: 37,
  },
  {
    location: Locations.Spain,
    direction: Directions.Forward,
    name: "Ascenso por valle el Gualet",
    distance: "7.00",
    id: 38,
  },
  {
    location: Locations.Spain,
    direction: Directions.Forward,
    name: "Viñedos dentro del valle Parra",
    distance: "6.81",
    id: 39,
  },
  {
    location: Locations.Spain,
    direction: Directions.Forward,
    name: "Viñedos Dardenyà",
    distance: "6.55",
    id: 40,
  },
  {
    location: Locations.Spain,
    direction: Directions.Forward,
    name: "Descenso por carretera",
    distance: "4.58",
    id: 41,
  },
  {
    location: Locations.Spain,
    direction: Directions.Reverse,
    name: "Final de Bellriu",
    distance: "14.34",
    id: 42,
  },
  {
    location: Locations.Spain,
    direction: Directions.Reverse,
    name: "Camino a Centenera",
    distance: "10.57",
    id: 43,
  },
  {
    location: Locations.Spain,
    direction: Directions.Reverse,
    name: "Salida desde Montverd",
    distance: "7.00",
    id: 44,
  },
  {
    location: Locations.Spain,
    direction: Directions.Reverse,
    name: "Ascenso bosque Montverd",
    distance: "6.81",
    id: 45,
  },
  {
    location: Locations.Spain,
    direction: Directions.Reverse,
    name: "Viñedos Dardenyà inversa",
    distance: "6.55",
    id: 46,
  },
  {
    location: Locations.Spain,
    direction: Directions.Reverse,
    name: "Subida por carretera",
    distance: "4.58",
    id: 47,
  },
  {
    location: Locations.USA,
    direction: Directions.Forward,
    name: "Beaver Creek Trail Forward",
    distance: "12.86",
    id: 48,
  },
  {
    location: Locations.USA,
    direction: Directions.Forward,
    name: "North Fork Pass",
    distance: "12.50",
    id: 49,
  },
  {
    location: Locations.USA,
    direction: Directions.Forward,
    name: "Hancock Creek Burst",
    distance: "6.89",
    id: 50,
  },
  {
    location: Locations.USA,
    direction: Directions.Forward,
    name: "Fuller Mountain Ascent",
    distance: "6.64",
    id: 51,
  },
  {
    location: Locations.USA,
    direction: Directions.Forward,
    name: "Tolt Valley Sprint Forward",
    distance: "6.10",
    id: 52,
  },
  {
    location: Locations.USA,
    direction: Directions.Forward,
    name: "Hancock Hill Sprint Forward",
    distance: "6.01",
    id: 53,
  },
  {
    location: Locations.USA,
    direction: Directions.Reverse,
    name: "Beaver Creek Trail Reverse",
    distance: "12.86",
    id: 54,
  },
  {
    location: Locations.USA,
    direction: Directions.Reverse,
    name: "North Fork Pass Reverse",
    distance: "12.50",
    id: 55,
  },
  {
    location: Locations.USA,
    direction: Directions.Reverse,
    name: "Fury Lake Depart",
    distance: "6.89",
    id: 56,
  },
  {
    location: Locations.USA,
    direction: Directions.Reverse,
    name: "Fuller Mountain Descent",
    distance: "6.64",
    id: 57,
  },
  {
    location: Locations.USA,
    direction: Directions.Reverse,
    name: "Tolt Valley Sprint Reverse",
    distance: "6.10",
    id: 58,
  },
  {
    location: Locations.USA,
    direction: Directions.Reverse,
    name: "Hancock Hill Sprint Reverse",
    distance: "6.01",
    id: 59,
  },
  {
    location: Locations.Poland,
    direction: Directions.Forward,
    name: "Zaróbka",
    distance: "16.46",
    id: 60,
  },
  {
    location: Locations.Poland,
    direction: Directions.Forward,
    name: "Zienki",
    distance: "13.42",
    id: 61,
  },
  {
    location: Locations.Poland,
    direction: Directions.Forward,
    name: "Marynka",
    distance: "9.25",
    id: 62,
  },
  {
    location: Locations.Poland,
    direction: Directions.Forward,
    name: "Kopina",
    distance: "7.03",
    id: 63,
  },
  {
    location: Locations.Poland,
    direction: Directions.Forward,
    name: "Lejno",
    distance: "6.72",
    id: 64,
  },
  {
    location: Locations.Poland,
    direction: Directions.Forward,
    name: "Czarny Las",
    distance: "6.62",
    id: 65,
  },
  {
    location: Locations.Poland,
    direction: Directions.Reverse,
    name: "Zagórze",
    distance: "16.46",
    id: 66,
  },
  {
    location: Locations.Poland,
    direction: Directions.Reverse,
    name: "Jezioro Rotcze",
    distance: "13.42",
    id: 67,
  },
  {
    location: Locations.Poland,
    direction: Directions.Reverse,
    name: "Borysik",
    distance: "9.25",
    id: 68,
  },
  {
    location: Locations.Poland,
    direction: Directions.Reverse,
    name: "Józefin",
    distance: "7.03",
    id: 69,
  },
  {
    location: Locations.Poland,
    direction: Directions.Reverse,
    name: "Jagodno",
    distance: "6.82",
    id: 70,
  },
  {
    location: Locations.Poland,
    direction: Directions.Reverse,
    name: "Jezioro Lukie",
    distance: "6.62",
    id: 71,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Vallée descendante",
    distance: "10.87",
    id: 72,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Pra d’Alart",
    distance: "9.83",
    id: 73,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Col de Turini - Départ en descente",
    distance: "6.85",
    id: 74,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Gordolon - Courte montée",
    distance: "5.17",
    id: 75,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Col de Turini sprint en montée",
    distance: "4.73",
    id: 76,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Forward,
    name: "Route de Turini Descente",
    distance: "3.95",
    id: 77,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Route de Turini",
    distance: "10.87",
    id: 78,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Col de Turini Départ",
    distance: "9.83",
    id: 79,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Route de Turini Montée",
    distance: "6.84",
    id: 80,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Col de Turini - Descente",
    distance: "5.17",
    id: 81,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Col de Turini - Sprint en descente",
    distance: "4.73",
    id: 82,
  },
  {
    location: Locations.Monaco,
    direction: Directions.Reverse,
    name: "Approche du Col de Turini - Montée",
    distance: "3.95",
    id: 83,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Forward,
    name: "Hamra",
    distance: "12.34",
    id: 84,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Forward,
    name: "Ransbysäter",
    distance: "11.98",
    id: 85,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Forward,
    name: "Elgsjön",
    distance: "7.28",
    id: 86,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Forward,
    name: "Stor-jangen Sprint",
    distance: "6.69",
    id: 87,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Forward,
    name: "Älgsjön Sprint",
    distance: "5.25",
    id: 88,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Forward,
    name: "Östra Hinnsjön",
    distance: "5.19",
    id: 89,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Reverse,
    name: "Lysvik",
    distance: "12.34",
    id: 90,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Reverse,
    name: "Norraskoga",
    distance: "11.98",
    id: 91,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Reverse,
    name: "Älgsjön",
    distance: "7.28",
    id: 92,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Reverse,
    name: "Stor-jangen Sprint Reverse",
    distance: "6.69",
    id: 93,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Reverse,
    name: "Skogsrallyt",
    distance: "5.25",
    id: 94,
  },
  {
    location: Locations.Sweden,
    direction: Directions.Reverse,
    name: "Björklangen",
    distance: "5.19",
    id: 95,
  },
  {
    location: Locations.Germany,
    direction: Directions.Forward,
    name: "Oberstein",
    distance: "11.67",
    id: 96,
  },
  {
    location: Locations.Germany,
    direction: Directions.Forward,
    name: "Hammerstein",
    distance: "10.81",
    id: 97,
  },
  {
    location: Locations.Germany,
    direction: Directions.Forward,
    name: "Kreuzungsring",
    distance: "6.31",
    id: 98,
  },
  {
    location: Locations.Germany,
    direction: Directions.Forward,
    name: "Verbundsring",
    distance: "5.85",
    id: 99,
  },
  {
    location: Locations.Germany,
    direction: Directions.Forward,
    name: "Innerer Feld-Sprint",
    distance: "5.56",
    id: 100,
  },
  {
    location: Locations.Germany,
    direction: Directions.Forward,
    name: "Waldaufstieg",
    distance: "5.39",
    id: 101,
  },
  {
    location: Locations.Germany,
    direction: Directions.Reverse,
    name: "Frauenberg",
    distance: "11.67",
    id: 102,
  },
  {
    location: Locations.Germany,
    direction: Directions.Reverse,
    name: "Ruschberg",
    distance: "10.70",
    id: 103,
  },
  {
    location: Locations.Germany,
    direction: Directions.Reverse,
    name: "Kreuzungsring reverse",
    distance: "6.31",
    id: 104,
  },
  {
    location: Locations.Germany,
    direction: Directions.Reverse,
    name: "Verbundsring Reverse",
    distance: "5.85",
    id: 105,
  },
  {
    location: Locations.Germany,
    direction: Directions.Reverse,
    name: "Innerer Feld-Sprint (umgekehrt)",
    distance: "5.56",
    id: 106,
  },
  {
    location: Locations.Germany,
    direction: Directions.Reverse,
    name: "Waldabstieg",
    distance: "5.39",
    id: 107,
  },
  {
    location: Locations.Finland,
    direction: Directions.Forward,
    name: "Kakaristo",
    distance: "16.20",
    id: 108,
  },
  {
    location: Locations.Finland,
    direction: Directions.Forward,
    name: "Kontinjärvi",
    distance: "15.05",
    id: 109,
  },
  {
    location: Locations.Finland,
    direction: Directions.Forward,
    name: "Kotajärvi",
    distance: "8.10",
    id: 110,
  },
  {
    location: Locations.Finland,
    direction: Directions.Forward,
    name: "Iso Oksjärvi",
    distance: "8.04",
    id: 111,
  },
  {
    location: Locations.Finland,
    direction: Directions.Forward,
    name: "Kailajärvi",
    distance: "7.51",
    id: 112,
  },
  {
    location: Locations.Finland,
    direction: Directions.Forward,
    name: "Naarajärvi",
    distance: "7.43",
    id: 113,
  },
  {
    location: Locations.Finland,
    direction: Directions.Reverse,
    name: "Pitkäjärvi",
    distance: "16.20",
    id: 114,
  },
  {
    location: Locations.Finland,
    direction: Directions.Reverse,
    name: "Hämelahti",
    distance: "14.96",
    id: 115,
  },
  {
    location: Locations.Finland,
    direction: Directions.Reverse,
    name: "Oksala",
    distance: "8.10",
    id: 116,
  },
  {
    location: Locations.Finland,
    direction: Directions.Reverse,
    name: "Järvenkylä",
    distance: "8.05",
    id: 117,
  },
  {
    location: Locations.Finland,
    direction: Directions.Reverse,
    name: "Jyrkysjärvi",
    distance: "7.55",
    id: 118,
  },
  {
    location: Locations.Finland,
    direction: Directions.Reverse,
    name: "Paskuri",
    distance: "7.34",
    id: 119,
  },
  {
    location: Locations.Greece,
    direction: Directions.Forward,
    name: "Anodou Farmakas",
    distance: "9.60",
    id: 120,
  },
  {
    location: Locations.Greece,
    direction: Directions.Forward,
    name: "Pomona Érixi",
    distance: "5.09",
    id: 121,
  },
  {
    location: Locations.Greece,
    direction: Directions.Forward,
    name: "Koryfi Dafni",
    distance: "4.50",
    id: 122,
  },
  {
    location: Locations.Greece,
    direction: Directions.Forward,
    name: "Perasma Platani",
    distance: "10.69",
    id: 123,
  },
  {
    location: Locations.Greece,
    direction: Directions.Forward,
    name: "Ourea Spevsi",
    distance: "5.74",
    id: 124,
  },
  {
    location: Locations.Greece,
    direction: Directions.Forward,
    name: "Abies Koiláda",
    distance: "7.09",
    id: 125,
  },
  {
    location: Locations.Greece,
    direction: Directions.Reverse,
    name: "Kathodo Leontiou",
    distance: "9.60",
    id: 126,
  },
  {
    location: Locations.Greece,
    direction: Directions.Reverse,
    name: "Fourkéta Kourva",
    distance: "4.50",
    id: 127,
  },
  {
    location: Locations.Greece,
    direction: Directions.Reverse,
    name: "Ampelonas Ormi",
    distance: "4.95",
    id: 128,
  },
  {
    location: Locations.Greece,
    direction: Directions.Reverse,
    name: "Tsiristra Théa",
    distance: "10.36",
    id: 129,
  },
  {
    location: Locations.Greece,
    direction: Directions.Reverse,
    name: "Pedines Epidaxi",
    distance: "5.38",
    id: 130,
  },
  {
    location: Locations.Greece,
    direction: Directions.Reverse,
    name: "Ypsona tou Dasos",
    distance: "6.59",
    id: 131,
  },
  {
    location: Locations.Wales,
    direction: Directions.Forward,
    name: "River Severn Valley",
    distance: "11.40",
    id: 132,
  },
  {
    location: Locations.Wales,
    direction: Directions.Forward,
    name: "Sweet Lamb",
    distance: "9.90",
    id: 133,
  },
  {
    location: Locations.Wales,
    direction: Directions.Forward,
    name: "Fferm Wynt",
    distance: "5.70",
    id: 134,
  },
  {
    location: Locations.Wales,
    direction: Directions.Forward,
    name: "Dyffryn Afon",
    distance: "5.70",
    id: 135,
  },
  {
    location: Locations.Wales,
    direction: Directions.Forward,
    name: "Bidno Moorland",
    distance: "4.90",
    id: 136,
  },
  {
    location: Locations.Wales,
    direction: Directions.Forward,
    name: "Pant Mawr",
    distance: "4.70",
    id: 137,
  },
  {
    location: Locations.Wales,
    direction: Directions.Reverse,
    name: "Bronfelen",
    distance: "11.40",
    id: 138,
  },
  {
    location: Locations.Wales,
    direction: Directions.Reverse,
    name: "Geufron Forest",
    distance: "10.00",
    id: 139,
  },
  {
    location: Locations.Wales,
    direction: Directions.Reverse,
    name: "Fferm Wynt Reverse",
    distance: "5.70",
    id: 140,
  },
  {
    location: Locations.Wales,
    direction: Directions.Reverse,
    name: "Dyffryn Afon Reverse",
    distance: "5.70",
    id: 141,
  },
  {
    location: Locations.Wales,
    direction: Directions.Reverse,
    name: "Bidno Moorland Reverse",
    distance: "4.80",
    id: 142,
  },
  {
    location: Locations.Wales,
    direction: Directions.Reverse,
    name: "Pant Mawr Reverse",
    distance: "5.10",
    id: 143,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Forward,
    name: "Newhouse Bridge",
    distance: "12.86",
    id: 144,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Forward,
    name: "South Morningside",
    distance: "12.58",
    id: 145,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Forward,
    name: "Annbank Station",
    distance: "7.77",
    id: 146,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Forward,
    name: "Rosebank Farm",
    distance: "7.16",
    id: 147,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Forward,
    name: "Old Butterstone Muir",
    distance: "5.82",
    id: 148,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Forward,
    name: "Glencastle Farm",
    distance: "5.25",
    id: 149,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Reverse,
    name: "Newhouse Bridge Reverse",
    distance: "12.98",
    id: 150,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Reverse,
    name: "South Morningside Reverse",
    distance: "12.66",
    id: 151,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Reverse,
    name: "Annbank Station Reverse",
    distance: "7.59",
    id: 152,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Reverse,
    name: "Rosebank Farm Reverse",
    distance: "6.96",
    id: 153,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Reverse,
    name: "Old Butterstone Muir Reverse",
    distance: "5.66",
    id: 154,
  },
  {
    location: Locations.Scotland,
    direction: Directions.Reverse,
    name: "Glencastle Farm Reverse",
    distance: "5.24",
    id: 155,
  },
];

// Scraper
// (() => {
//   let location = "";
//   let direction = "";
//   let stage = false;
//   let distance = "";
//
//   console.log(
//     JSON.stringify(
//       [...document.querySelectorAll(".wikitable:nth-of-type(2)  td")].reduce(
//         (acc, val) => {
//           if (val.rowSpan === 12) {
//             location = val.innerHTML;
//             return acc;
//           }
//
//           if (val.rowSpan === 6) {
//             direction = val.innerHTML;
//             return acc;
//           }
//
//           if (!stage) {
//             stage = val.innerHTML;
//             return acc;
//           } else {
//             distance = val.innerHTML;
//             const result = { location, direction, stage, distance };
//             stage = false;
//             return [...acc, result];
//           }
//         },
//         []
//       ).map((s, idx) => ({...s, id: idx}))
//     )
//   );
// })();
